"""
A .docx letterhead, and a text box: what is redacted and what is refused.

:func:`batch.write_approved_docx` re-scans the redacted document and refuses to
write if anything identifying survives. Two places text can hide used to defeat
both detection and that scan, so an approved .docx went out with the clinic
name, clinician, address, postcode and phone still on it.

The two are not the same problem, because the redactor can reach one and not the
other:

* **Header and footer text is reachable.** ``ingest._extract_docx`` now reads it,
  so a letterhead is detected, shown to the reviewer, and redacted like anything
  else -- the document comes out usable *and* clean.
* **A text box is not reachable.** ``apply_redactions`` cannot rewrite text
  inside a ``w:txbxContent``, so there is nothing to do but refuse the write.
  Refusing is the safe failure: the clinician keeps the original and is told why.

The backstop test near the end is the one that matters most. It proves the
residual sweep still guards the header now that detection also covers it, by
handing ``write_approved_docx`` a map the reviewer has stripped down.

Every name, number and address here is fabricated.
"""

from __future__ import annotations

import io
import zipfile

import docx
import pytest
from docx.oxml import parse_xml

from carescribe.core import batch, deidentify, ingest

BODY_PATIENT = "Wilhelmina Featherstonehaugh"
# The detected span covers the name only, never the title -- the title is
# regenerated by variant expansion -- so the two are named separately here.
HEADER_CLINICIAN_NAME = "Archibald Pemberton-Fitzroy"
HEADER_CLINICIAN = f"Dr {HEADER_CLINICIAN_NAME}"
FOOTER_MRN = "ZZ1122334"
FOOTER_ADDRESS = "14 Rosemary Gardens, Bolton BL1 4AB"
FOOTER_PHONE = "01204 555123"
BOX_CLINICIAN = "Dr Millicent Thorncastle"
BOX_MRN = "ZZ7766554"
BOX_PHONE = "01204 555999"

HEADER = f"St Elsewhere Clinic - {HEADER_CLINICIAN}"
# "Our ref" rather than a bare "Ref": the possessive is what makes it an
# identifier field rather than prose, and it is what a real letterhead uses.
FOOTER = f"Our ref {FOOTER_MRN} - {FOOTER_ADDRESS} - tel {FOOTER_PHONE}"
BOX = f"Referrer {BOX_CLINICIAN}, MRN {BOX_MRN}, tel {BOX_PHONE}"

# A VML text box. DrawingML shapes wrap their text in the same w:txbxContent
# tag, so covering this shape covers both.
_TEXT_BOX_XML = """
<w:pict xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
        xmlns:v="urn:schemas-microsoft-com:vml">
  <v:shape><v:textbox><w:txbxContent>
    <w:p><w:r><w:t>{text}</w:t></w:r></w:p>
  </w:txbxContent></v:textbox></v:shape>
</w:pict>
"""


def _document(*, header: str = "", footer: str = "", text_box: str = "") -> bytes:
    """A .docx whose body is ordinary and whose extras are the thing under test."""
    document = docx.Document()
    document.add_paragraph(f"Patient: {BODY_PATIENT}")
    document.add_paragraph("Impression: stable, discharged on sertraline 50mg.")
    if text_box:
        run = document.add_paragraph().add_run()
        run._r.append(parse_xml(_TEXT_BOX_XML.format(text=text_box)))
    section = document.sections[0]
    if header:
        section.header.paragraphs[0].text = header
    if footer:
        section.footer.paragraphs[0].text = footer
    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _detected(source_bytes: bytes, tmp_path) -> dict[str, str]:
    """Run the flow the app runs: read the file, de-identify, keep the map."""
    path = tmp_path / "source.docx"
    path.write_bytes(source_bytes)
    result = deidentify.deidentify(ingest.extract_text(str(path)))
    return result.phi_map


def _write(source_bytes: bytes, tmp_path, replacements: dict[str, str] | None = None):
    if replacements is None:
        replacements = {v: k for k, v in _detected(source_bytes, tmp_path).items()}
    return batch.write_approved_docx(
        "letterhead.docx", source_bytes, replacements, output_dir=tmp_path / "out"
    )


def _xml_of(path) -> str:
    with zipfile.ZipFile(path) as archive:
        return " ".join(
            archive.read(name).decode("utf-8", "replace")
            for name in archive.namelist()
            if name.endswith(".xml")
        )


# ==========================================================================
# Header and footer: reachable, so detected and redacted
# ==========================================================================


@pytest.mark.parametrize(
    "identifier", [HEADER_CLINICIAN_NAME, FOOTER_MRN, FOOTER_ADDRESS, FOOTER_PHONE]
)
def test_letterhead_identifiers_are_detected(identifier, tmp_path):
    """None of these was extracted at all before the header/footer read."""
    detected = " | ".join(
        _detected(_document(header=HEADER, footer=FOOTER), tmp_path).values()
    )
    assert identifier in detected


def test_the_letterhead_document_writes_and_nothing_leaks(tmp_path):
    """The whole point: a letterhead is redacted, not a document you cannot use."""
    written = _write(_document(header=HEADER, footer=FOOTER), tmp_path)
    assert written.exists()

    xml = _xml_of(written)
    for identifier in (
        BODY_PATIENT,
        HEADER_CLINICIAN,
        FOOTER_MRN,
        FOOTER_PHONE,
        "Rosemary Gardens",
        "BL1 4AB",
    ):
        assert identifier not in xml


# ==========================================================================
# A text box: unreachable, so refused
# ==========================================================================


def test_text_box_identifiers_are_never_detected(tmp_path):
    """python-docx's paragraph walk does not descend into a w:txbxContent."""
    detected = " | ".join(_detected(_document(text_box=BOX), tmp_path).values())
    for identifier in (BOX_CLINICIAN, BOX_MRN, BOX_PHONE):
        assert identifier not in detected


def test_a_text_box_refuses_the_write(tmp_path):
    """Before the fix this call succeeded and wrote the box's contents to disk."""
    with pytest.raises(batch.BatchError, match="Refusing to write the Word file") as caught:
        _write(_document(text_box=BOX), tmp_path)
    assert BOX_MRN in str(caught.value)


def test_nothing_reaches_disk_when_the_write_is_refused(tmp_path):
    with pytest.raises(batch.BatchError):
        _write(_document(text_box=BOX), tmp_path)
    assert list((tmp_path / "out").glob("*.docx")) == []


# ==========================================================================
# The sweep still backstops the header, now that detection also covers it
# ==========================================================================


def test_a_header_identifier_missing_from_the_map_still_refuses(tmp_path):
    """Detection covering the header must not retire the residual sweep.

    Simulates the reviewer dismissing the header's clinician: the value is left
    out of the approved map, so redaction leaves it standing and the sweep is the
    only thing between it and the output file.
    """
    source = _document(header=HEADER, footer=FOOTER)
    replacements = {v: k for k, v in _detected(source, tmp_path).items()}
    stripped = {
        value: placeholder
        for value, placeholder in replacements.items()
        if HEADER_CLINICIAN_NAME not in value
    }
    assert stripped != replacements  # the map really did lose something

    with pytest.raises(batch.BatchError, match="Refusing to write the Word file"):
        _write(source, tmp_path, stripped)
    assert list((tmp_path / "out").glob("*.docx")) == []


# ==========================================================================
# Guards: a fix that refused every .docx would pass everything above
# ==========================================================================


def test_a_document_with_no_extras_still_writes(tmp_path):
    assert _write(_document(), tmp_path).exists()


def test_a_benign_header_and_footer_do_not_trip_the_scan(tmp_path):
    written = _write(
        _document(header="Clinical Record - Page 1", footer="Confidential"), tmp_path
    )
    assert written.exists()


def test_a_benign_text_box_does_not_trip_the_scan(tmp_path):
    written = _write(_document(text_box="Please file in the patient record."), tmp_path)
    assert written.exists()
