"""Community mental health / psychology encounters."""

from __future__ import annotations

from finetune.datagen.sampling import Choice, Subset
from finetune.datagen.schema import EncounterType

from .base import Vignette, med

VIGNETTES = [
    Vignette(
        id="cmht_depression_followup",
        specialty="community mental health",
        encounter_type=EncounterType.FOLLOW_UP,
        weight=1.3,
        demographics={
            "age_band": Choice(["18-29", "30-39", "40-49", "50-59"]),
            "sex": Choice(["M", "F"]),
            "occupation": Choice(["unemployed", "part-time retail", "administrator", "carer"]),
        },
        presenting_complaint="review of moderate depressive episode, 6 weeks into treatment",
        history=[
            {"label": "mood", "detail": Choice(["slightly improved", "unchanged", "brighter, more engaged"])},
            {"label": "sleep", "detail": Choice(["still early-morning waking", "improving"])},
            {"label": "risk", "detail": "no active suicidal ideation, no plans or intent"},
        ],
        pmh=Subset(["previous depressive episode", "generalised anxiety disorder"], 0, 2),
        meds=[med("sertraline", Choice(["50mg", "100mg"]), "OD")],
        allergies=[],
        examination=[
            {"system": "mental state", "finding": "affect", "value": "reactive, mildly low"},
            {"system": "mental state", "finding": "thought", "value": "no psychotic features"},
            {"system": "mental state", "finding": "cognition", "value": "grossly intact"},
        ],
        investigations=[],
        impression=["moderate depressive episode, partial response to SSRI"],
        plan=[
            {"action": "increase sertraline", "detail": "to 100mg OD, review tolerability"},
            {"action": "psychological therapy", "detail": "continue weekly CBT"},
            {"action": "safety plan", "detail": "reviewed and updated with patient"},
        ],
        follow_up="3 weeks",
        gappable=("pmh", "follow_up"),
    ),
    Vignette(
        id="cmht_crisis_contact",
        specialty="community mental health",
        encounter_type=EncounterType.CRISIS,
        weight=0.8,
        demographics={
            "age_band": Choice(["18-29", "30-39"]),
            "sex": Choice(["M", "F"]),
            "occupation": Choice(["student", "unemployed", "hospitality"]),
        },
        presenting_complaint="urgent review after presenting to crisis line with rising distress",
        history=[
            {"label": "trigger", "detail": Choice(["relationship breakdown", "job loss", "anniversary of bereavement"])},
            {"label": "risk", "detail": "fleeting thoughts of self-harm, no act, future-oriented, agrees to safety plan"},
            {"label": "supports", "detail": "staying with a friend tonight"},
        ],
        pmh=["emotionally unstable personality traits"],
        meds=[med("mirtazapine", "30mg", "ON")],
        allergies=[],
        examination=[
            {"system": "mental state", "finding": "affect", "value": "distressed, tearful, settles during contact"},
            {"system": "mental state", "finding": "risk", "value": "dynamic, currently low-moderate"},
        ],
        investigations=[],
        impression=["acute-on-chronic distress, no indication for admission"],
        plan=[
            {"action": "home treatment team", "detail": "daily contact for 72 hours"},
            {"action": "safety plan", "detail": "written copy given, crisis numbers confirmed"},
            {"action": "review medication", "detail": "no change today"},
        ],
        follow_up="telephone contact tomorrow morning",
        gappable=("investigations",),
    ),
    Vignette(
        id="cmht_anxiety_new",
        specialty="community mental health",
        encounter_type=EncounterType.NEW,
        weight=1.1,
        demographics={
            "age_band": Choice(["18-29", "30-39", "40-49"]),
            "sex": Choice(["M", "F"]),
            "occupation": Choice(["student", "administrator", "self-employed", "teacher"]),
        },
        presenting_complaint="first assessment for persistent worry and physical tension",
        history=[
            {"label": "duration", "detail": Choice(["most days for six months", "worsening over the past year"])},
            {"label": "symptoms", "detail": "restlessness, poor concentration, muscle tension, initial insomnia"},
            {"label": "avoidance", "detail": Choice(["avoids work presentations", "avoids crowded places", "no significant avoidance"])},
            {"label": "risk", "detail": "no suicidal ideation, no self-harm, no risk to others"},
        ],
        pmh=Subset(["irritable bowel syndrome", "migraine"], 0, 2),
        meds=[],
        allergies=[],
        examination=[
            {"system": "mental state", "finding": "appearance", "value": "well kempt, restless in chair"},
            {"system": "mental state", "finding": "affect", "value": "anxious, reactive"},
            {"system": "mental state", "finding": "thought", "value": "worry themes, no obsessions, no psychotic features"},
        ],
        investigations=[],
        impression=["generalised anxiety disorder, moderate severity"],
        plan=[
            {"action": "psychoeducation", "detail": "anxiety cycle explained, written material given"},
            {"action": "refer for CBT", "detail": "added to psychological therapies waiting list"},
            {"action": "discuss medication", "detail": "SSRI option outlined, patient prefers therapy first"},
        ],
        follow_up=Choice(["6 weeks", "8 weeks"]),
        gappable=("pmh", "investigations", "follow_up"),
    ),
    Vignette(
        id="cmht_ptsd_assessment",
        specialty="community mental health",
        encounter_type=EncounterType.NEW,
        weight=0.9,
        demographics={
            "age_band": Choice(["30-39", "40-49", "50-59"]),
            "sex": Choice(["M", "F"]),
            "occupation": Choice(["paramedic", "security officer", "unemployed", "warehouse operative"]),
        },
        presenting_complaint="assessment following referral for intrusive memories after a workplace incident",
        history=[
            {"label": "index event", "detail": "a serious incident at work, details not explored in depth today"},
            {"label": "symptoms", "detail": Choice(["nightmares and intrusive images most nights", "flashbacks triggered by sirens"])},
            {"label": "avoidance", "detail": "avoids the workplace and conversations about the incident"},
            {"label": "risk", "detail": "denies suicidal intent, reports hopelessness at times, engages well"},
        ],
        pmh=Subset(["previous depressive episode", "alcohol use above recommended limits"], 0, 2),
        meds=[],
        allergies=[],
        examination=[
            {"system": "mental state", "finding": "affect", "value": "guarded initially, more open later in interview"},
            {"system": "mental state", "finding": "arousal", "value": "hypervigilant, startles at corridor noise"},
            {"system": "mental state", "finding": "cognition", "value": "attention reduced, orientation intact"},
        ],
        investigations=[],
        impression=["post-traumatic stress disorder, meets criteria on history"],
        plan=[
            {"action": "refer for trauma-focused therapy", "detail": "EMDR or trauma-focused CBT"},
            {"action": "sleep advice", "detail": "sleep hygiene discussed, no hypnotic prescribed"},
            {"action": "alcohol brief intervention", "detail": "current intake reviewed with the patient"},
        ],
        follow_up="4 weeks",
        gappable=("pmh", "investigations"),
    ),
    Vignette(
        id="cmht_discharge_to_gp",
        specialty="community mental health",
        encounter_type=EncounterType.DISCHARGE,
        weight=1.0,
        demographics={
            "age_band": Choice(["30-39", "40-49", "50-59"]),
            "sex": Choice(["M", "F"]),
            "occupation": Choice(["administrator", "part-time retail", "carer", "back at work full time"]),
        },
        presenting_complaint="discharge review after sustained recovery from a depressive episode",
        history=[
            {"label": "mood", "detail": "euthymic for three months"},
            {"label": "function", "detail": Choice(["returned to work", "resumed social contact", "managing household routines"])},
            {"label": "risk", "detail": "no suicidal ideation throughout the treatment episode"},
        ],
        pmh=["moderate depressive episode"],
        meds=[med("sertraline", Choice(["100mg", "150mg"]), "OD")],
        allergies=[],
        examination=[
            {"system": "mental state", "finding": "affect", "value": "euthymic, full range"},
            {"system": "mental state", "finding": "thought", "value": "no ruminative or psychotic content"},
        ],
        investigations=[],
        impression=["depressive episode in remission, ready for discharge to primary care"],
        plan=[
            {"action": "discharge to GP", "detail": "continue current antidepressant for at least six months"},
            {"action": "relapse plan", "detail": "early warning signs written down with the patient"},
            {"action": "re-referral route", "detail": "GP may re-refer directly if symptoms return"},
        ],
        follow_up=Choice([None, "GP review in 3 months"]),
        gappable=("investigations", "follow_up"),
    ),
    Vignette(
        id="cmht_caseload_handover",
        specialty="community mental health",
        encounter_type=EncounterType.HANDOVER,
        weight=0.8,
        demographics={
            "age_band": Choice(["18-29", "30-39", "40-49"]),
            "sex": Choice(["M", "F"]),
            "occupation": Choice(["unemployed", "hospitality", "student"]),
        },
        presenting_complaint="handover to a new care coordinator, no change in presentation this week",
        history=[
            {"label": "engagement", "detail": Choice(["attends most appointments", "variable engagement, responds to text reminders"])},
            {"label": "mood", "detail": Choice(["low but stable", "improving slowly"])},
            {"label": "risk", "detail": "historical self-harm, none in the past four months, safety plan in place"},
            {"label": "social", "detail": Choice(["supported housing", "living with family", "housing application pending"])},
        ],
        pmh=["recurrent depressive disorder"],
        meds=[med("mirtazapine", Choice(["30mg", "45mg"]), "ON")],
        allergies=[],
        examination=[
            {"system": "mental state", "finding": "affect", "value": "flat but reactive"},
            {"system": "mental state", "finding": "risk", "value": "chronic, currently low"},
        ],
        investigations=[],
        impression=["stable on current plan, continuity of care the main priority"],
        plan=[
            {"action": "introduce new care coordinator", "detail": "joint appointment arranged"},
            {"action": "continue medication", "detail": "no change at handover"},
            {"action": "safety plan", "detail": "copy shared with the incoming coordinator"},
        ],
        follow_up="within 2 weeks with the new coordinator",
        gappable=("investigations", "history"),
    ),
]
